channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - igdiscover==0.15.1
  - pandas
  - pip
  - r-rmarkdown
  - r-dplyr
  - r-ggplot2
  - r-data.table
  - r-r.utils
  - r-tidyr
