channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - igdiscover
  - pandas
  - r-rmarkdown
  - r-dplyr
  - r-ggplot2
  - r-data.table
  - r-r.utils
  - r-tidyr
  - pip:
    - 'git+https://github.com/NBISweden/IgDiscover.git@clonoquery2'
