channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - igdiscover==0.15.1
  - pandas
  - pip
  - snakemake-minimal=5.10.0
  - r-rmarkdown
  - r-dplyr
  - r-ggplot2
  - r-data.table
  - r-r.utils
  - r-tidyr
