name: CI

on: [push]

jobs:
  run:
    name: Run pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Conda environment
        run: |
          conda info
          conda install --quiet -n base conda-libmamba-solver
          conda config --set solver libmamba
          source $CONDA/etc/profile.d/conda.sh
          conda env create --quiet -n testenv -f environment.yml
      - name: Run pipeline
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          ./test.sh
