name: CI

on: [push]

jobs:
  run:
    name: Run pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Conda environment
        run: |
          # Pin due to a possible bug in Mamba 0.22.1
          conda install -c conda-forge mamba=0.15.3
          source $CONDA/etc/profile.d/conda.sh
          mamba env create --quiet -n testenv -f environment.yml
      - name: Run pipeline
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          ./test.sh
